name: Update badges

on:
  schedule:
    # Runs at 2am UTC
    - cron: "0 * * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: sandeep-kunusoth # optional, but default will use the same from github
